### ISSUE TITLE
権限レベルごとのコマンド表示の変更

### ISSUE THREAD

**Issue by Celesteria-154** [Celesteria-154/CivilizationWarsPlugins#4]
USER,ADMIN(,MOD使うかも？)

**Comment by iruru1111** [comment]
実はゲームシステムの方はOP権限を持っていてもデバッグログは表示されないようになっているんですよね
"Admin"というタグを持っているプレイヤーに対してデバッグログが表示されるようにしています
(β0.1.3;/function game:cmd/change_adminで変更化)
タグにまで対応させられたら嬉しいですけど難しそうですね…
